// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: BatteryChecker

#ifndef _BATTERYCHECKER_UI_H
#define _BATTERYCHECKER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_FrontScreen
void ui_FrontScreen_screen_init(void);
void ui_event_FrontScreen(lv_event_t * e);
extern lv_obj_t * ui_FrontScreen;
extern lv_obj_t * ui_PercentValue;
extern lv_obj_t * ui_PercentSign;
extern lv_obj_t * ui_BatteryIndicator;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_fullbattery_png);    // assets/FullBattery.png
LV_IMG_DECLARE(ui_img_halfbattery_png);    // assets/HalfBattery.png
LV_IMG_DECLARE(ui_img_emptybattery_png);    // assets/EmptyBattery.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
