// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: BatteryChecker

#ifndef _UI_COMP_BATTERYINDICATOR_H
#define _UI_COMP_BATTERYINDICATOR_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT BatteryIndicator
#define UI_COMP_BATTERYINDICATOR_BATTERYINDICATOR 0
#define _UI_COMP_BATTERYINDICATOR_NUM 1
lv_obj_t * ui_BatteryIndicator_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
