// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: BatteryChecker

#include "ui.h"


// COMPONENT BatteryIndicator

lv_obj_t * ui_BatteryIndicator_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_BatteryIndicator;
    cui_BatteryIndicator = lv_image_create(comp_parent);
    lv_image_set_src(cui_BatteryIndicator, &ui_img_fullbattery_png);
    lv_obj_set_width(cui_BatteryIndicator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_BatteryIndicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_BatteryIndicator, -5);
    lv_obj_set_y(cui_BatteryIndicator, -20);
    lv_obj_set_align(cui_BatteryIndicator, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_BatteryIndicator, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_BatteryIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(cui_BatteryIndicator, 2700);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BATTERYINDICATOR_NUM);
    children[UI_COMP_BATTERYINDICATOR_BATTERYINDICATOR] = cui_BatteryIndicator;
    lv_obj_add_event_cb(cui_BatteryIndicator, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_BatteryIndicator, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_BatteryIndicator_create_hook(cui_BatteryIndicator);
    return cui_BatteryIndicator;
}

