// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: BatteryChecker

#include "ui.h"

/* void RetrieveBatteryPercent(lv_event_t * e)
{
	// Your code here
} */
