// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SmartWatch_Project_V1

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ClockExampleScreen
void ui_ClockExampleScreen_screen_init(void);
void ui_event_ClockExampleScreen(lv_event_t * e);
lv_obj_t * ui_ClockExampleScreen;
lv_obj_t * ui_ClockDigitalDisplay;
lv_obj_t * ui_DigitalDisplayMinuteLeftDigit;
lv_obj_t * ui_DigitalDisplayHoursRightDigit;
lv_obj_t * ui_DigitalDisplayHoursLeftDigit;
lv_obj_t * ui_DigitalDisplayMinuteRightDigit;
lv_obj_t * ui_ClockSecondHandImage;
lv_obj_t * ui_ClockMinuteHandImage;
lv_obj_t * ui_ClockHourHandImage;
lv_obj_t * ui_CenterAxis;
void ui_event_CenterButton(lv_event_t * e);
lv_obj_t * ui_CenterButton;
// CUSTOM VARIABLES


// SCREEN: ui_SetTimeScreen
void ui_SetTimeScreen_screen_init(void);
void ui_event_SetTimeScreen(lv_event_t * e);
lv_obj_t * ui_SetTimeScreen;
lv_obj_t * ui_DigitalClockSet;
lv_obj_t * ui_SetTimeScreenColonLabel;
lv_obj_t * ui_SetTimeScreenHourLabel;
lv_obj_t * ui_SetTimeScreenMinuteLabel;
void ui_event_SetTimeScreenMinuteDownBtn(lv_event_t * e);
lv_obj_t * ui_SetTimeScreenMinuteDownBtn;
void ui_event_SetTimeScreenMinuteUpBtn(lv_event_t * e);
lv_obj_t * ui_SetTimeScreenMinuteUpBtn;
void ui_event_SetTimeScreenHourUpBtn(lv_event_t * e);
lv_obj_t * ui_SetTimeScreenHourUpBtn;
void ui_event_SetTimeScreenHourDownBtn(lv_event_t * e);
lv_obj_t * ui_SetTimeScreenHourDownBtn;
// CUSTOM VARIABLES


// SCREEN: ui_SleepMode
void ui_SleepMode_screen_init(void);
void ui_event_SleepMode(lv_event_t * e);
lv_obj_t * ui_SleepMode;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ClockExampleScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_SetTimeScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SetTimeScreen_screen_init);
    }
}

void ui_event_CenterButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SleepMode, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_SleepMode_screen_init);
        DisplaySleep(e);
    }
}

void ui_event_SetTimeScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_ClockExampleScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ClockExampleScreen_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        ResetSecond(e);
    }
}

void ui_event_SetTimeScreenMinuteDownBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        TimeSetMinuteDown(e);
    }
}

void ui_event_SetTimeScreenMinuteUpBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        TimeSetMinuteUp(e);
    }
}

void ui_event_SetTimeScreenHourUpBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        TimeSetHourUp(e);
    }
}

void ui_event_SetTimeScreenHourDownBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        TimeSetHourDown(e);
    }
}

void ui_event_SleepMode(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ClockExampleScreen, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_ClockExampleScreen_screen_init);
        DisplayWakeup(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ClockExampleScreen_screen_init();
    ui_SetTimeScreen_screen_init();
    ui_SleepMode_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ClockExampleScreen);
}
