// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SmartWatch_Project_V1

#ifndef _SMARTWATCH_PROJECT_V1_UI_H
#define _SMARTWATCH_PROJECT_V1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_ClockExampleScreen
void ui_ClockExampleScreen_screen_init(void);
void ui_event_ClockExampleScreen(lv_event_t * e);
extern lv_obj_t * ui_ClockExampleScreen;
extern lv_obj_t * ui_ClockDigitalDisplay;
extern lv_obj_t * ui_DigitalDisplayMinuteLeftDigit;
extern lv_obj_t * ui_DigitalDisplayHoursRightDigit;
extern lv_obj_t * ui_DigitalDisplayHoursLeftDigit;
extern lv_obj_t * ui_DigitalDisplayMinuteRightDigit;
extern lv_obj_t * ui_ClockSecondHandImage;
extern lv_obj_t * ui_ClockMinuteHandImage;
extern lv_obj_t * ui_ClockHourHandImage;
extern lv_obj_t * ui_CenterAxis;
void ui_event_CenterButton(lv_event_t * e);
extern lv_obj_t * ui_CenterButton;
// CUSTOM VARIABLES

// SCREEN: ui_SetTimeScreen
void ui_SetTimeScreen_screen_init(void);
void ui_event_SetTimeScreen(lv_event_t * e);
extern lv_obj_t * ui_SetTimeScreen;
extern lv_obj_t * ui_DigitalClockSet;
extern lv_obj_t * ui_SetTimeScreenColonLabel;
extern lv_obj_t * ui_SetTimeScreenHourLabel;
extern lv_obj_t * ui_SetTimeScreenMinuteLabel;
void ui_event_SetTimeScreenMinuteDownBtn(lv_event_t * e);
extern lv_obj_t * ui_SetTimeScreenMinuteDownBtn;
void ui_event_SetTimeScreenMinuteUpBtn(lv_event_t * e);
extern lv_obj_t * ui_SetTimeScreenMinuteUpBtn;
void ui_event_SetTimeScreenHourUpBtn(lv_event_t * e);
extern lv_obj_t * ui_SetTimeScreenHourUpBtn;
void ui_event_SetTimeScreenHourDownBtn(lv_event_t * e);
extern lv_obj_t * ui_SetTimeScreenHourDownBtn;
// CUSTOM VARIABLES

// SCREEN: ui_SleepMode
void ui_SleepMode_screen_init(void);
void ui_event_SleepMode(lv_event_t * e);
extern lv_obj_t * ui_SleepMode;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_base_png);    // assets/Base.png
LV_IMG_DECLARE(ui_img_290762000);    // assets/24-hour display.png
LV_IMG_DECLARE(ui_img_second_hand_png);    // assets/Second Hand.png
LV_IMG_DECLARE(ui_img_minute_hand_png);    // assets/Minute Hand.png
LV_IMG_DECLARE(ui_img_hour_hand_png);    // assets/Hour Hand.png
LV_IMG_DECLARE(ui_img_axel_point_png);    // assets/Axel point.png
LV_IMG_DECLARE(ui_img_arrow_png);    // assets/Arrow.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
