// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SmartWatch_Project_V1

#include "ui.h"

void ui_ClockExampleScreen_screen_init(void)
{
    ui_ClockExampleScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ClockExampleScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ClockExampleScreen, lv_color_hex(0x373737), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ClockExampleScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_ClockExampleScreen, &ui_img_base_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ClockExampleScreen, lv_color_hex(0x323431), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ClockExampleScreen, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ClockDigitalDisplay = lv_image_create(ui_ClockExampleScreen);
    lv_image_set_src(ui_ClockDigitalDisplay, &ui_img_290762000);
    lv_obj_set_width(ui_ClockDigitalDisplay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockDigitalDisplay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockDigitalDisplay, 0);
    lv_obj_set_y(ui_ClockDigitalDisplay, 40);
    lv_obj_set_align(ui_ClockDigitalDisplay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ClockDigitalDisplay, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ClockDigitalDisplay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DigitalDisplayMinuteLeftDigit = lv_label_create(ui_ClockDigitalDisplay);
    lv_obj_set_width(ui_DigitalDisplayMinuteLeftDigit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DigitalDisplayMinuteLeftDigit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DigitalDisplayMinuteLeftDigit, 10);
    lv_obj_set_y(ui_DigitalDisplayMinuteLeftDigit, 2);
    lv_obj_set_align(ui_DigitalDisplayMinuteLeftDigit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DigitalDisplayMinuteLeftDigit, "0");

    ui_DigitalDisplayHoursRightDigit = lv_label_create(ui_ClockDigitalDisplay);
    lv_obj_set_width(ui_DigitalDisplayHoursRightDigit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DigitalDisplayHoursRightDigit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DigitalDisplayHoursRightDigit, -10);
    lv_obj_set_y(ui_DigitalDisplayHoursRightDigit, 2);
    lv_obj_set_align(ui_DigitalDisplayHoursRightDigit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DigitalDisplayHoursRightDigit, "2");

    ui_DigitalDisplayHoursLeftDigit = lv_label_create(ui_ClockDigitalDisplay);
    lv_obj_set_width(ui_DigitalDisplayHoursLeftDigit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DigitalDisplayHoursLeftDigit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DigitalDisplayHoursLeftDigit, -30);
    lv_obj_set_y(ui_DigitalDisplayHoursLeftDigit, 2);
    lv_obj_set_align(ui_DigitalDisplayHoursLeftDigit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DigitalDisplayHoursLeftDigit, "1");

    ui_DigitalDisplayMinuteRightDigit = lv_label_create(ui_ClockDigitalDisplay);
    lv_obj_set_width(ui_DigitalDisplayMinuteRightDigit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DigitalDisplayMinuteRightDigit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DigitalDisplayMinuteRightDigit, 30);
    lv_obj_set_y(ui_DigitalDisplayMinuteRightDigit, 2);
    lv_obj_set_align(ui_DigitalDisplayMinuteRightDigit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DigitalDisplayMinuteRightDigit, "0");

    ui_ClockSecondHandImage = lv_image_create(ui_ClockExampleScreen);
    lv_image_set_src(ui_ClockSecondHandImage, &ui_img_second_hand_png);
    lv_obj_set_width(ui_ClockSecondHandImage, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_ClockSecondHandImage, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_ClockSecondHandImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ClockSecondHandImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ClockSecondHandImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ClockMinuteHandImage = lv_image_create(ui_ClockExampleScreen);
    lv_image_set_src(ui_ClockMinuteHandImage, &ui_img_minute_hand_png);
    lv_obj_set_width(ui_ClockMinuteHandImage, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_ClockMinuteHandImage, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_ClockMinuteHandImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ClockMinuteHandImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ClockMinuteHandImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ClockHourHandImage = lv_image_create(ui_ClockExampleScreen);
    lv_image_set_src(ui_ClockHourHandImage, &ui_img_hour_hand_png);
    lv_obj_set_width(ui_ClockHourHandImage, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_ClockHourHandImage, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_ClockHourHandImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ClockHourHandImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ClockHourHandImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CenterAxis = lv_image_create(ui_ClockExampleScreen);
    lv_image_set_src(ui_CenterAxis, &ui_img_axel_point_png);
    lv_obj_set_width(ui_CenterAxis, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CenterAxis, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CenterAxis, -1);
    lv_obj_set_y(ui_CenterAxis, 2);
    lv_obj_set_align(ui_CenterAxis, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CenterAxis, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_CenterAxis, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CenterButton = lv_button_create(ui_ClockExampleScreen);
    lv_obj_set_width(ui_CenterButton, 160);
    lv_obj_set_height(ui_CenterButton, 160);
    lv_obj_set_align(ui_CenterButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CenterButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CenterButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CenterButton, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_CenterButton, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_CenterButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CenterButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_CenterButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_CenterButton, 10, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_CenterButton, ui_event_CenterButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ClockExampleScreen, ui_event_ClockExampleScreen, LV_EVENT_ALL, NULL);

}
