// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SmartWatch_Project_V1

#include "ui.h"

void DisplaySleepCheck(lv_event_t * e)
{
	// Your code here
}

void ResetSecond(lv_event_t * e)
{
	// Your code here
}

void TimeSetMinuteDown(lv_event_t * e)
{
	// Your code here
}

void TimeSetMinuteUp(lv_event_t * e)
{
	// Your code here
}

void TimeSetHourUp(lv_event_t * e)
{
	// Your code here
}

void TimeSetHourDown(lv_event_t * e)
{
	// Your code here
}

void OnHomeScreen(lv_event_t * e)
{
	// Your code here
}

void OffHomeScreen(lv_event_t * e)
{
	// Your code here
}

void DisplaySleep(lv_event_t * e)
{
	// Your code here
}

void DisplayWakeup(lv_event_t * e)
{
	// Your code here
}
