// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SmartWatch_Project_V1

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void DisplaySleep(lv_event_t * e);
void ResetSecond(lv_event_t * e);
void TimeSetMinuteDown(lv_event_t * e);
void TimeSetMinuteUp(lv_event_t * e);
void TimeSetHourUp(lv_event_t * e);
void TimeSetHourDown(lv_event_t * e);
void DisplayWakeup(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
