// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SmartWatch_Project_V1

#include "ui.h"

void ui_SleepMode_screen_init(void)
{
    ui_SleepMode = lv_obj_create(NULL);
    lv_obj_add_state(ui_SleepMode, LV_STATE_PRESSED);       /// States
    lv_obj_remove_flag(ui_SleepMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SleepMode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SleepMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SleepMode, ui_event_SleepMode, LV_EVENT_ALL, NULL);

}
