// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SmartWatch_Project_V1

#include "ui.h"

void ui_SetTimeScreen_screen_init(void)
{
    ui_SetTimeScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SetTimeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetTimeScreen, lv_color_hex(0x313431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetTimeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DigitalClockSet = lv_obj_create(ui_SetTimeScreen);
    lv_obj_set_width(ui_DigitalClockSet, 140);
    lv_obj_set_height(ui_DigitalClockSet, 50);
    lv_obj_set_align(ui_DigitalClockSet, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DigitalClockSet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_DigitalClockSet, lv_color_hex(0x313431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DigitalClockSet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_DigitalClockSet, 80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetTimeScreenColonLabel = lv_label_create(ui_SetTimeScreen);
    lv_obj_set_width(ui_SetTimeScreenColonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetTimeScreenColonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SetTimeScreenColonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetTimeScreenColonLabel, ":");
    lv_obj_set_style_text_color(ui_SetTimeScreenColonLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SetTimeScreenColonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SetTimeScreenColonLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetTimeScreenHourLabel = lv_label_create(ui_SetTimeScreen);
    lv_obj_set_width(ui_SetTimeScreenHourLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetTimeScreenHourLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetTimeScreenHourLabel, -25);
    lv_obj_set_y(ui_SetTimeScreenHourLabel, 0);
    lv_obj_set_align(ui_SetTimeScreenHourLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetTimeScreenHourLabel, "12");
    lv_obj_set_style_text_color(ui_SetTimeScreenHourLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SetTimeScreenHourLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SetTimeScreenHourLabel, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetTimeScreenMinuteLabel = lv_label_create(ui_SetTimeScreen);
    lv_obj_set_width(ui_SetTimeScreenMinuteLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetTimeScreenMinuteLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetTimeScreenMinuteLabel, 30);
    lv_obj_set_y(ui_SetTimeScreenMinuteLabel, 0);
    lv_obj_set_align(ui_SetTimeScreenMinuteLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetTimeScreenMinuteLabel, "00");
    lv_obj_set_style_text_color(ui_SetTimeScreenMinuteLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SetTimeScreenMinuteLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SetTimeScreenMinuteLabel, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetTimeScreenMinuteDownBtn = lv_button_create(ui_SetTimeScreen);
    lv_obj_set_width(ui_SetTimeScreenMinuteDownBtn, 60);
    lv_obj_set_height(ui_SetTimeScreenMinuteDownBtn, 28);
    lv_obj_set_x(ui_SetTimeScreenMinuteDownBtn, 0);
    lv_obj_set_y(ui_SetTimeScreenMinuteDownBtn, -28);
    lv_obj_set_align(ui_SetTimeScreenMinuteDownBtn, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_SetTimeScreenMinuteDownBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SetTimeScreenMinuteDownBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetTimeScreenMinuteDownBtn, lv_color_hex(0x313431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetTimeScreenMinuteDownBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_SetTimeScreenMinuteDownBtn, &ui_img_arrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SetTimeScreenMinuteDownBtn, lv_color_hex(0x313431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SetTimeScreenMinuteDownBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SetTimeScreenMinuteDownBtn, lv_color_hex(0x313431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SetTimeScreenMinuteDownBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SetTimeScreenMinuteDownBtn, lv_color_hex(0x313431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SetTimeScreenMinuteDownBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_SetTimeScreenMinuteDownBtn, 1800, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetTimeScreenMinuteUpBtn = lv_button_create(ui_SetTimeScreen);
    lv_obj_set_width(ui_SetTimeScreenMinuteUpBtn, 60);
    lv_obj_set_height(ui_SetTimeScreenMinuteUpBtn, 28);
    lv_obj_set_x(ui_SetTimeScreenMinuteUpBtn, 30);
    lv_obj_set_y(ui_SetTimeScreenMinuteUpBtn, -50);
    lv_obj_set_align(ui_SetTimeScreenMinuteUpBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SetTimeScreenMinuteUpBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SetTimeScreenMinuteUpBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetTimeScreenMinuteUpBtn, lv_color_hex(0x313431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetTimeScreenMinuteUpBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_SetTimeScreenMinuteUpBtn, &ui_img_arrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SetTimeScreenMinuteUpBtn, lv_color_hex(0x313431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SetTimeScreenMinuteUpBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SetTimeScreenMinuteUpBtn, lv_color_hex(0x313431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SetTimeScreenMinuteUpBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SetTimeScreenMinuteUpBtn, lv_color_hex(0x313431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SetTimeScreenMinuteUpBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetTimeScreenHourUpBtn = lv_button_create(ui_SetTimeScreen);
    lv_obj_set_width(ui_SetTimeScreenHourUpBtn, 60);
    lv_obj_set_height(ui_SetTimeScreenHourUpBtn, 28);
    lv_obj_set_x(ui_SetTimeScreenHourUpBtn, -30);
    lv_obj_set_y(ui_SetTimeScreenHourUpBtn, -50);
    lv_obj_set_align(ui_SetTimeScreenHourUpBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SetTimeScreenHourUpBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SetTimeScreenHourUpBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetTimeScreenHourUpBtn, lv_color_hex(0x313431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetTimeScreenHourUpBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_SetTimeScreenHourUpBtn, &ui_img_arrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SetTimeScreenHourUpBtn, lv_color_hex(0x313431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SetTimeScreenHourUpBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SetTimeScreenHourUpBtn, lv_color_hex(0x313431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SetTimeScreenHourUpBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SetTimeScreenHourUpBtn, lv_color_hex(0x313431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SetTimeScreenHourUpBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetTimeScreenHourDownBtn = lv_button_create(ui_SetTimeScreen);
    lv_obj_set_width(ui_SetTimeScreenHourDownBtn, 60);
    lv_obj_set_height(ui_SetTimeScreenHourDownBtn, 28);
    lv_obj_set_x(ui_SetTimeScreenHourDownBtn, -30);
    lv_obj_set_y(ui_SetTimeScreenHourDownBtn, 50);
    lv_obj_set_align(ui_SetTimeScreenHourDownBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SetTimeScreenHourDownBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SetTimeScreenHourDownBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetTimeScreenHourDownBtn, lv_color_hex(0x313431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetTimeScreenHourDownBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_SetTimeScreenHourDownBtn, &ui_img_arrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SetTimeScreenHourDownBtn, lv_color_hex(0x313431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SetTimeScreenHourDownBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SetTimeScreenHourDownBtn, lv_color_hex(0x313431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SetTimeScreenHourDownBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SetTimeScreenHourDownBtn, lv_color_hex(0x313431), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SetTimeScreenHourDownBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_SetTimeScreenHourDownBtn, 1800, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_pivot_x(ui_SetTimeScreenHourDownBtn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_pivot_y(ui_SetTimeScreenHourDownBtn, 14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SetTimeScreenMinuteDownBtn, ui_event_SetTimeScreenMinuteDownBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SetTimeScreenMinuteUpBtn, ui_event_SetTimeScreenMinuteUpBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SetTimeScreenHourUpBtn, ui_event_SetTimeScreenHourUpBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SetTimeScreenHourDownBtn, ui_event_SetTimeScreenHourDownBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SetTimeScreen, ui_event_SetTimeScreen, LV_EVENT_ALL, NULL);

}
